number1 = float(input("Enter first number: "))
number2 = float(input("Enter second number: "))
number3 = float(input("Enter third number: "))
largest = max(number1, number2, number3)
smallest = min(number1, number2, number3)
print("Largest:", largest)
print("Smallest:", smallest)